import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Question} from "../components/Question/Question";

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>Music Wars</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Music Wars 🎵
                </h1>

                <p className={styles.description}>
                    Давайте определим уровень музыкальных знаний
                </p>

                <Question/>

            </main>
        </div>
    )
}
