import Head from 'next/head'
import styles from '../styles/Home.module.css'
import {Intro} from "../components/Intro/Intro";
import {profileState$} from "../models/profile";
import { useStore } from 'effector-react';
import {Main} from "../components/Main/Main";

export default function Home() {
    const {level} = useStore(profileState$);
    return (
        <div className={styles.container}>
            <Head>
                <title>Music Wars</title>
                <meta name="description" content="Generated by create next app"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>

            {level ? <Main /> : <Intro/>}
        </div>
    )
}
